name: Maven CI/CD
on:
 push:
    branches: [ master ]
jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 14

    - name: Build project with Maven
      run: |
          mvn -B package --file pom.xml
          mvn org.apache.maven.plugins:maven-help-plugin:2.1.1:evaluate \
          -Dexpression=project.version
          project_version= $(mvn org.apache.maven.plugins:maven-help-plugin:2.1.1:evaluate \
          -Dexpression=project.version)
          echo $project_version
